### ISSUE TITLE
missing hiera lookup_options

### ISSUE THREAD

**Issue by brightdroid** [voxpupuli/puppet-systemd#196]
Please add merge options, so one can add entries in all hiera layers.

Example:
---
You have three hiera layers (common, env, node) and you'd like to merge "systemd::loginctl_users" from env and node, it's currently not possible.

Solution
---
common.yaml:
```yaml
# ...
lookup_options:
  systemd::loginctl_users:
    merge: deep
# ...
```

Docs: https://puppet.com/docs/puppet/7.6/hiera_merging.html#setting_lookup_options_to_refine_the_result_of_a_lookup

Thank you
