### ISSUE TITLE
loginctl disable-linger runs even when disabled

### ISSUE THREAD

**Issue by jcpunk** [voxpupuli/puppet-systemd#301]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:7.17.0
- Ruby:ruby-3.0.4-160.el9_0.x86_64
- Distribution: AlmaLinux 9
- Module version: 3.10.0

## How to reproduce (e.g Puppet code you use)

```yaml
stdlib::manage::create_resources:
  loginctl_user:
    sysoptmgmt:
      linger: disabled

```

## What are you seeing

Every puppet run sets this to `disabled` even though it is already disabled.  Seems like the check to see if it is already disabled isn't actually working....

## What behaviour did you expect instead

Already disabled linger users shouldn't trigger a corrective action

## Output log

```
Notice: /Stage[main]/Stdlib::Manage/Loginctl_user[sysoptmgmt]/linger: defined 'linger' as 'disabled' (corrective)
```
