### ISSUE TITLE
Add possibiliry to setup limits for user sessions

### ISSUE THREAD

**Issue by ondrejv2** [voxpupuli/puppet-systemd#417]
In service-limits.pp I see:

https://github.com/voxpupuli/puppet-systemd/blob/bcec820dfc7188f75b579f4a67e14ea1b71861e0/manifests/service_limits.pp#L46-L48

But I need to set limits for user slices, i.e. "user-.slice.d".

Please ad support for user slice limits

**Comment by ondrejv2** [comment]
Correct, `MemoryMax` , `CPUWeight` , are most useful here

**Comment by ondrejv2** [comment]
Quick question, how do I apply these settings via hiera?
Tried:
```
systemd::dropin_files:
  'user-limits.conf':
    unit: 'user-.slice'
    slice_entry:
        'MemoryMax': '17G'
```
but it does not work
