### ISSUE TITLE
Add hiera-friendly option to manage dropins

### ISSUE THREAD

**Issue by ondrejv2** [voxpupuli/puppet-systemd#435]
As per recently closed #420 we have a nice option to manage user slices etc, but the only way to make real use of it is via different module.
I would like to use this capability via Hiera - i.e. the way I'd expect it to work is something like this:

```yaml
systemd::dropin_files:
  'user-limits.conf':
    unit: 'user-.slice'
    slice_entry:
        'MemoryMax': '17G'
```

but this obviously does not work as `systemd::dropin_files` does not load `systemd::manage_dropin` class and even if it did, the class does not create resources from hiera.

This is a friendly request improve the code to make it overall more hiera-friendly.
